# syntax=docker/dockerfile:1.7
FROM golang:1.25 AS builder
WORKDIR /build
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download
COPY . .
ARG SERVICE_PATH
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=linux go build -o /build/bootstrap ${SERVICE_PATH}
FROM public.ecr.aws/lambda/provided:al2023
COPY --from=builder /build/bootstrap ${LAMBDA_RUNTIME_DIR}/bootstrap
CMD ["bootstrap"]
