table_name	create_statement
transactions	"CREATE TABLE public.transactions (
	id UUID NOT NULL DEFAULT gen_random_uuid(),
	step INT8 NOT NULL,
	type STRING NOT NULL,
	amount FLOAT8 NOT NULL,
	name_orig STRING NOT NULL,
	old_balance_orig FLOAT8 NOT NULL,
	new_balance_orig FLOAT8 NOT NULL,
	name_dest STRING NOT NULL,
	old_balance_dest FLOAT8 NOT NULL,
	new_balance_dest FLOAT8 NOT NULL,
	error_balance_orig FLOAT8 NOT NULL,
	error_balance_dest FLOAT8 NOT NULL,
	risk_score FLOAT8 NOT NULL,
	risk_tier STRING NOT NULL,
	is_fraud_label BOOL NOT NULL,
	arrived_at TIMESTAMPTZ NOT NULL DEFAULT now():::TIMESTAMPTZ,
	processed_at TIMESTAMPTZ NULL,
	CONSTRAINT transactions_pkey PRIMARY KEY (id ASC),
	INDEX transactions_risk_tier_arrived_at_idx (risk_tier ASC, arrived_at DESC),
	INDEX transactions_name_orig_idx (name_orig ASC),
	INDEX transactions_name_dest_idx (name_dest ASC),
	INDEX transactions_step_type_idx (step ASC, type ASC),
	CONSTRAINT type_check CHECK (type IN ('TRANSFER':::STRING, 'CASH_OUT':::STRING)),
	CONSTRAINT tier_check CHECK (risk_tier IN ('low':::STRING, 'medium':::STRING, 'high':::STRING))
) WITH (schema_locked = true) LOCALITY REGIONAL BY TABLE IN PRIMARY REGION;"
table_name	create_statement
tasks	"CREATE TABLE public.tasks (
	id UUID NOT NULL DEFAULT gen_random_uuid(),
	transaction_id UUID NOT NULL,
	risk_score FLOAT8 NOT NULL,
	status STRING NOT NULL DEFAULT 'pending':::STRING,
	claimed_by STRING NULL,
	claimed_at TIMESTAMPTZ NULL,
	heartbeat_at TIMESTAMPTZ NULL,
	completed_at TIMESTAMPTZ NULL,
	step STRING NULL,
	scratchpad JSONB NULL,
	verdict STRING NULL,
	confidence FLOAT8 NULL,
	reviewed_by STRING NULL,
	reviewed_at TIMESTAMPTZ NULL,
	review_decision STRING NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now():::TIMESTAMPTZ,
	CONSTRAINT tasks_pkey PRIMARY KEY (id ASC),
	CONSTRAINT tasks_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id),
	UNIQUE INDEX tasks_transaction_id_key (transaction_id ASC),
	INDEX tasks_status_created_at_idx (status ASC, created_at ASC) WHERE status = 'pending':::STRING,
	INDEX tasks_heartbeat_at_idx (heartbeat_at ASC) WHERE status IN ('claimed':::STRING, 'investigating':::STRING),
	INDEX tasks_status_completed_at_idx (status ASC, completed_at DESC),
	INDEX tasks_verdict_completed_at_idx (verdict ASC, completed_at DESC) WHERE verdict IS NOT NULL,
	INDEX tasks_status_idx (status ASC) WHERE status = 'pending_review':::STRING,
	CONSTRAINT status_check CHECK (status IN ('pending':::STRING, 'claimed':::STRING, 'investigating':::STRING, 'done':::STRING, 'failed':::STRING, 'escalated':::STRING, 'pending_review':::STRING)),
	CONSTRAINT verdict_check CHECK ((verdict IS NULL) OR (verdict IN ('fraud':::STRING, 'legit':::STRING, 'escalate':::STRING))),
	CONSTRAINT review_decision_check CHECK ((review_decision IS NULL) OR (review_decision IN ('approved':::STRING, 'rejected':::STRING)))
) WITH (schema_locked = true) LOCALITY REGIONAL BY TABLE IN PRIMARY REGION;"
table_name	create_statement
case_memory	"CREATE TABLE public.case_memory (
	id UUID NOT NULL DEFAULT gen_random_uuid(),
	summary STRING NOT NULL,
	verdict STRING NOT NULL,
	confidence_avg FLOAT8 NULL,
	pattern_type STRING NULL,
	key_signals STRING[] NULL,
	transaction_type STRING NULL,
	amount_range STRING NULL,
	error_orig_sign STRING NULL,
	error_dest_sign STRING NULL,
	embedding VECTOR(1024) NULL,
	salience FLOAT8 NOT NULL DEFAULT 1.0:::FLOAT8,
	recall_count INT8 NOT NULL DEFAULT 0:::INT8,
	merge_count INT8 NOT NULL DEFAULT 1:::INT8,
	archived BOOL NOT NULL DEFAULT false,
	source_task_id UUID NULL,
	data_source STRING NOT NULL DEFAULT 'paysim':::STRING,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now():::TIMESTAMPTZ,
	last_recalled_at TIMESTAMPTZ NULL,
	last_merged_at TIMESTAMPTZ NULL,
	CONSTRAINT case_memory_pkey PRIMARY KEY (id ASC),
	VECTOR INDEX case_memory_embedding_idx (embedding vector_l2_ops) WHERE archived = false,
	INDEX case_memory_transaction_type_verdict_archived_idx (transaction_type ASC, verdict ASC, archived ASC),
	INDEX case_memory_pattern_type_verdict_idx (pattern_type ASC, verdict ASC) WHERE archived = false,
	INDEX case_memory_salience_last_recalled_at_idx (salience ASC, last_recalled_at ASC) WHERE archived = false,
	CONSTRAINT verdict_ck CHECK (verdict IN ('fraud':::STRING, 'legit':::STRING, 'escalate':::STRING)),
	CONSTRAINT salience_ck CHECK ((salience >= 0.0:::FLOAT8) AND (salience <= 2.0:::FLOAT8)),
	CONSTRAINT type_ck CHECK ((transaction_type IS NULL) OR (transaction_type IN ('TRANSFER':::STRING, 'CASH_OUT':::STRING)))
) WITH (schema_locked = true) LOCALITY REGIONAL BY TABLE IN PRIMARY REGION;"
table_name	create_statement
audit_log	"CREATE TABLE public.audit_log (
	id UUID NOT NULL DEFAULT gen_random_uuid(),
	task_id UUID NOT NULL,
	transaction_id UUID NOT NULL,
	agent_id STRING NOT NULL,
	action STRING NOT NULL,
	reasoning STRING NULL,
	memory_hits INT8 NULL,
	similarity_scores FLOAT8[] NULL,
	tokens_in INT8 NULL,
	tokens_out INT8 NULL,
	bedrock_model STRING NULL,
	latency_ms INT8 NULL,
	reviewer_id STRING NULL,
	review_notes STRING NULL,
	evidence_s3_key STRING NULL,
	context_snapshot JSONB NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now():::TIMESTAMPTZ,
	CONSTRAINT audit_log_pkey PRIMARY KEY (id ASC),
	CONSTRAINT audit_log_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id),
	CONSTRAINT audit_log_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id),
	INDEX audit_log_task_id_created_at_idx (task_id ASC, created_at ASC),
	INDEX audit_log_agent_id_created_at_idx (agent_id ASC, created_at DESC),
	INDEX audit_log_action_created_at_idx (action ASC, created_at DESC),
	INDEX audit_log_bedrock_model_created_at_idx (bedrock_model ASC, created_at DESC) WHERE tokens_in IS NOT NULL,
	CONSTRAINT action_ck CHECK (action IN ('mcp_query':::STRING, 'memory_recall':::STRING, 'bedrock_reasoning':::STRING, 'verdict_fraud':::STRING, 'verdict_legit':::STRING, 'verdict_escalate':::STRING, 'auto_approve':::STRING, 'auto_block':::STRING, 'task_claimed':::STRING, 'task_resumed':::STRING, 'task_failed':::STRING, 'task_requeued':::STRING, 'human_reviewed':::STRING))
) WITH (schema_locked = true) LOCALITY REGIONAL BY TABLE IN PRIMARY REGION;"
